#this i also got from kubernetes documentation   
#(https://kubernetes.io/docs/concepts/services-networking/service/)
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
spec: 
  ports:
  - port: 3500
    protocol: TCP
  type: ClusterIP
  selector:
    role: api